[package]
name = "e2e-test"
version = "0.3.1"
edition = "2018"
license-file = "../LICENSE"
publish = false

[dependencies]
radius = { version = "0.3.1", path = "../radius" }
tokio = { version = "1.6.1", features = ["signal", "net"] }
async-trait = "0.1.50"
